"""widen nationality and country_of_residence columns

Revision ID: 445402baca5a
Revises: c5a0fc10b9a3
Create Date: 2026-07-17 10:53:44.125788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445402baca5a'
down_revision = 'c5a0fc10b9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sanctioned_entities', schema=None) as batch_op:
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('country_of_residence',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sanctioned_entities', schema=None) as batch_op:
        batch_op.alter_column('country_of_residence',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
        batch_op.alter_column('nationality',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
