"""initial schema

Revision ID: c5a0fc10b9a3
Revises: 
Create Date: 2026-07-17 11:37:20.101556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a0fc10b9a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_reference', sa.String(length=128), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('proof_token_hash', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('age_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_age_verifications_subject_reference'), ['subject_reference'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('developer_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_email', sa.String(length=256), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('developer_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developer_projects_api_key_hash'), ['api_key_hash'], unique=True)

    op.create_table('list_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_ownership_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('wallet_ownership_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_ownership_challenges_address'), ['address'], unique=False)

    op.create_table('wallet_ownership_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('transfer_amount_eur', sa.Float(), nullable=True),
    sa.Column('threshold_eur', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('wallet_ownership_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_ownership_verifications_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_ownership_verifications_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('age_verification_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('subject_reference', sa.String(length=128), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=256), nullable=False),
    sa.Column('request_value', sa.Text(), nullable=True),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['age_verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('age_verification_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_age_verification_sessions_subject_reference'), ['subject_reference'], unique=False)

    op.create_table('sanctioned_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_entity_id', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('primary_name', sa.String(length=256), nullable=False),
    sa.Column('date_of_birth', sa.String(length=32), nullable=True),
    sa.Column('place_of_birth', sa.String(length=256), nullable=True),
    sa.Column('nationality', sa.String(length=4), nullable=True),
    sa.Column('country_of_residence', sa.String(length=4), nullable=True),
    sa.Column('national_ids', sa.JSON(), nullable=True),
    sa.Column('addresses', sa.JSON(), nullable=True),
    sa.Column('programs', sa.JSON(), nullable=True),
    sa.Column('lei', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_record', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['list_snapshot_id'], ['list_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('counterparty_name', sa.String(length=256), nullable=True),
    sa.Column('counterparty_lei', sa.String(length=32), nullable=True),
    sa.Column('list_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('transfer_action_sent', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('human_override', sa.Boolean(), nullable=False),
    sa.Column('human_override_by', sa.String(length=128), nullable=True),
    sa.Column('human_override_decision', sa.String(length=16), nullable=True),
    sa.Column('human_override_reason', sa.Text(), nullable=True),
    sa.Column('human_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_request_raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['list_snapshot_id'], ['list_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screening_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_decisions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('entity_name_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name_text', sa.String(length=256), nullable=False),
    sa.Column('name_normalized', sa.String(length=256), nullable=False),
    sa.Column('phonetic_key', sa.String(length=64), nullable=False),
    sa.Column('name_type', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctioned_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_name_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_name_index_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_name_index_phonetic_key'), ['phonetic_key'], unique=False)

    op.create_table('screening_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_decision_id', sa.Integer(), nullable=False),
    sa.Column('party_role', sa.String(length=24), nullable=False),
    sa.Column('sanctioned_entity_id', sa.Integer(), nullable=True),
    sa.Column('matched_name_variant', sa.String(length=256), nullable=True),
    sa.Column('name_score', sa.Float(), nullable=False),
    sa.Column('corroborating_fields_matched', sa.JSON(), nullable=True),
    sa.Column('rule_branch', sa.String(length=64), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sanctioned_entity_id'], ['sanctioned_entities.id'], ),
    sa.ForeignKeyConstraint(['screening_decision_id'], ['screening_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_matches')
    with op.batch_alter_table('entity_name_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_name_index_phonetic_key'))
        batch_op.drop_index(batch_op.f('ix_entity_name_index_name_normalized'))

    op.drop_table('entity_name_index')
    with op.batch_alter_table('screening_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_decisions_transaction_id'))

    op.drop_table('screening_decisions')
    op.drop_table('sanctioned_entities')
    with op.batch_alter_table('age_verification_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_age_verification_sessions_subject_reference'))

    op.drop_table('age_verification_sessions')
    with op.batch_alter_table('wallet_ownership_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_ownership_verifications_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_ownership_verifications_address'))

    op.drop_table('wallet_ownership_verifications')
    with op.batch_alter_table('wallet_ownership_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_ownership_challenges_address'))

    op.drop_table('wallet_ownership_challenges')
    op.drop_table('list_snapshots')
    with op.batch_alter_table('developer_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developer_projects_api_key_hash'))

    op.drop_table('developer_projects')
    op.drop_table('audit_log')
    with op.batch_alter_table('age_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_age_verifications_subject_reference'))

    op.drop_table('age_verifications')
    # ### end Alembic commands ###
