"""add developer_project_id tenant isolation columns

Revision ID: d40d886adbab
Revises: 445402baca5a
Create Date: 2026-09-12 19:11:30.838072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40d886adbab'
down_revision = '445402baca5a'
branch_labels = None
depends_on = None


def upgrade():
    # This project is still pre-production: no real customer data exists in
    # wallet_ownership/age-verify tables yet, only local dev/test rows from
    # earlier manual verification sessions. developer_project_id is added
    # NOT NULL below (every row must have an owning tenant going forward),
    # so any pre-existing row -- which predates the tenant-isolation
    # feature and has no owner to backfill -- is cleared here rather than
    # given a fake placeholder project. Child-before-parent order avoids
    # the age_verification_sessions -> age_verifications FK violating.
    op.execute("DELETE FROM age_verification_sessions")
    op.execute("DELETE FROM age_verifications")
    op.execute("DELETE FROM wallet_ownership_verifications")
    op.execute("DELETE FROM wallet_ownership_challenges")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_project_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['developer_project_id'], ['developer_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_usage_events_developer_project_id'), ['developer_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_usage_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_billing_usage_events_project_occurred', ['developer_project_id', 'occurred_at'], unique=False)

    with op.batch_alter_table('age_verification_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer_project_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_age_verification_sessions_developer_project_id'), ['developer_project_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_age_verification_sessions_developer_project_id', 'developer_projects', ['developer_project_id'], ['id']
        )

    with op.batch_alter_table('age_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer_project_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_age_verifications_developer_project_id'), ['developer_project_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_age_verifications_developer_project_id', 'developer_projects', ['developer_project_id'], ['id']
        )

    with op.batch_alter_table('developer_projects', schema=None) as batch_op:
        # server_default backfills existing rows (registered before billing
        # existed) to the "free" plan; the application-level default in the
        # model is what new rows use from here on.
        batch_op.add_column(sa.Column('plan_status', sa.String(length=16), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('plan_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_developer_projects_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_unique_constraint('uq_developer_projects_stripe_subscription_id', ['stripe_subscription_id'])

    with op.batch_alter_table('wallet_ownership_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer_project_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_wallet_ownership_challenges_developer_project_id'), ['developer_project_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_wallet_ownership_challenges_developer_project_id', 'developer_projects', ['developer_project_id'], ['id']
        )

    with op.batch_alter_table('wallet_ownership_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer_project_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_wallet_ownership_verifications_developer_project_id'), ['developer_project_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_wallet_ownership_verifications_developer_project_id', 'developer_projects', ['developer_project_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_ownership_verifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wallet_ownership_verifications_developer_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wallet_ownership_verifications_developer_project_id'))
        batch_op.drop_column('developer_project_id')

    with op.batch_alter_table('wallet_ownership_challenges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wallet_ownership_challenges_developer_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wallet_ownership_challenges_developer_project_id'))
        batch_op.drop_column('developer_project_id')

    with op.batch_alter_table('developer_projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_developer_projects_stripe_subscription_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_developer_projects_stripe_customer_id'))
        batch_op.drop_column('plan_updated_at')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('plan_status')

    with op.batch_alter_table('age_verifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_age_verifications_developer_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_age_verifications_developer_project_id'))
        batch_op.drop_column('developer_project_id')

    with op.batch_alter_table('age_verification_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_age_verification_sessions_developer_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_age_verification_sessions_developer_project_id'))
        batch_op.drop_column('developer_project_id')

    with op.batch_alter_table('billing_usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_billing_usage_events_project_occurred')
        batch_op.drop_index(batch_op.f('ix_billing_usage_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_billing_usage_events_developer_project_id'))

    op.drop_table('billing_usage_events')
    # ### end Alembic commands ###
