"""Golden-vector tests proving byte-exact HMAC interop with envoy's Go
implementation (pkg/webhook/auth.go). The vectors below were generated by a
standalone Go program implementing the exact same algorithm (crypto/hmac +
crypto/sha256 + base64.RawURLEncoding) read directly from that source file --
see the project plan for details. If these pass, our Python verifier accepts
a real Envoy-signed request; if Envoy's RequireServerAuth is enabled, the
signer tests below prove our replies would pass Envoy's own verification
too (by symmetry: same algorithm, same key, same header-order convention).
"""

import hashlib
import hmac as hmac_stdlib

import pytest

from app.webhook.auth import HMACError, HMACSigner, HMACToken, verify_request

KEY_HEX = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
KEY = bytes.fromhex(KEY_HEX)
KEY_ID = "01JXTESTKEYID0000000000000"
TRANSFER_ID = "11111111-1111-1111-1111-111111111111"
TIMESTAMP = "2026-07-14T12:00:00Z"

# Captured verbatim from a real Go run of the algorithm in auth.go.
GOLDEN_AUTH_TWO_HEADERS = (
    "HMAC sig=DJeKdIMrsmWaTHX_eZXkpNHmyxL2ImZst2C7AOKf5jQ, "
    "nonce=bJXq7DBGuywWuzWjzZ7oFQ, "
    "headers=x-transfer-id;x-transfer-timestamp, "
    "kid=01JXTESTKEYID0000000000000"
)
GOLDEN_AUTH_ONE_HEADER = (
    "HMAC sig=6UEOADMj8wNmLC3YQiIlDRCmodkRPod7ptmU7ev-wno, "
    "nonce=nM_TaM5p2PNR6kEqfThLrw, "
    "headers=x-transfer-id, "
    "kid=01JXTESTKEYID0000000000000"
)


def _headers_for(extra=None):
    headers = {
        "x-transfer-id": TRANSFER_ID,
        "x-transfer-timestamp": TIMESTAMP,
    }
    if extra:
        headers.update(extra)
    return headers.get


def test_verify_go_generated_two_header_vector():
    """The core interop proof: a real Go-signed Authorization header, with
    the exact same key, must verify successfully in Python."""
    verify_request(GOLDEN_AUTH_TWO_HEADERS, _headers_for(), KEY_ID, KEY)


def test_verify_go_generated_one_header_vector():
    get_header = lambda name: TRANSFER_ID if name == "x-transfer-id" else None
    verify_request(GOLDEN_AUTH_ONE_HEADER, get_header, KEY_ID, KEY)


def test_verify_rejects_wrong_key():
    wrong_key = bytes(32)
    with pytest.raises(HMACError):
        verify_request(GOLDEN_AUTH_TWO_HEADERS, _headers_for(), KEY_ID, wrong_key)


def test_verify_rejects_tampered_header_value():
    get_header = _headers_for({"x-transfer-id": "22222222-2222-2222-2222-222222222222"})
    with pytest.raises(HMACError):
        verify_request(GOLDEN_AUTH_TWO_HEADERS, get_header, KEY_ID, KEY)


def test_verify_rejects_unknown_key_id():
    with pytest.raises(HMACError):
        verify_request(GOLDEN_AUTH_TWO_HEADERS, _headers_for(), "some-other-key-id", KEY)


def test_verify_fails_closed_when_unconfigured():
    with pytest.raises(HMACError):
        verify_request(GOLDEN_AUTH_TWO_HEADERS, _headers_for(), "", b"")


def test_verify_fails_closed_when_header_missing():
    with pytest.raises(HMACError):
        verify_request(None, _headers_for(), KEY_ID, KEY)


def test_verify_rejects_malformed_header():
    with pytest.raises(HMACError):
        verify_request("Bearer sometoken", _headers_for(), KEY_ID, KEY)


def test_signer_produces_a_verifiable_token_round_trip():
    """Python-signs, Python-verifies: proves our signer and verifier agree,
    independent of the Go vectors above."""
    signer = HMACSigner(KEY_ID, KEY)
    signer.append("X-Transfer-ID", TRANSFER_ID)
    signer.append("X-Transfer-Timestamp", TIMESTAMP)
    auth_header = signer.authorization()

    verify_request(auth_header, _headers_for(), KEY_ID, KEY)


def test_signer_matches_go_signature_shape():
    """Confirms our signer's raw HMAC-SHA256 computation matches the same
    stdlib primitive Go uses, over data constructed the same way (nonce +
    concatenated raw header values), by recomputing independently here."""
    signer = HMACSigner(KEY_ID, KEY)
    signer.append("X-Transfer-ID", TRANSFER_ID)
    signer.append("X-Transfer-Timestamp", TIMESTAMP)

    expected_data = signer.nonce + TRANSFER_ID.encode() + TIMESTAMP.encode()
    expected_sig = hmac_stdlib.new(KEY, expected_data, hashlib.sha256).digest()

    token = HMACToken.parse(signer.authorization())
    assert token.signature == expected_sig
